export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

<nav style={{ position: "absolute", top: 20, right: 40 }}>
  <a href="/" style={{ marginRight: 10 }}>EN</a>
  <a href="/ru">RU</a>
</nav>export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
